import { Threat, MonitoredSystem, SecurityEvent } from '../types';

export const seedThreats: Threat[] = [
  {
    id: 'THREAT-001',
    name: 'Credential Attack',
    risk: 'HIGH',
    riskScore: 87,
    confidence: 94,
    currentStage: 'Initial Access',
    currentStageId: 'initial-access',
    nextLikelyStage: 'Credential Access',
    nextLikelyProbability: 78,
    firstDetected: '2026-09-02 23:42:01',
    lastSeen: '1 min ago (23:48:12)',
    affectedSystem: 'DC-01',
    affectedSystemIp: '10.0.4.12',
    sourceIp: '194.26.29.114',
    threatActor: 'UNC-2452 / APT Affiliate Pattern',
    status: 'Active',
    attackType: 'Credential Stuffing & Kerberoasting Vector',
    summary: 'Multiple failed Kerberos pre-authentication attempts from an unknown external IP address followed by a successful logon into the privileged "svc_backup_admin" service account.',
    stages: [
      {
        id: 'reconnaissance',
        name: 'Reconnaissance',
        order: 1,
        status: 'completed',
        timestamp: '23:42:01',
        confidence: 96,
        mitreTechniqueId: 'T1595.002',
        mitreTechniqueName: 'Active Scanning: Vulnerability Scanning',
        description: 'External scanning host conducted port enumeration against domain controller service ports (88, 389, 445).',
        indicators: ['SYN stealth scan observed', 'TCP 88/389 port sweep', 'Source IP 194.26.29.114 flagged in AlienVault OTX'],
        relatedEventsCount: 2,
      },
      {
        id: 'initial-access',
        name: 'Initial Access',
        order: 2,
        status: 'current',
        timestamp: '23:48:12',
        confidence: 94,
        mitreTechniqueId: 'T1078.002',
        mitreTechniqueName: 'Valid Accounts: Domain Accounts',
        description: 'Authentication succeeded for privileged service account svc_backup_admin following 8 failed logon attempts.',
        indicators: ['Kerberos pre-auth failure burst', 'EventID 4625 followed by 4624', 'Unregistered device TLS JA4 fingerprint'],
        relatedEventsCount: 4,
      },
      {
        id: 'execution',
        name: 'Execution',
        order: 3,
        status: 'predicted',
        confidence: 62,
        mitreTechniqueId: 'T1059.001',
        mitreTechniqueName: 'Command and Scripting Interpreter: PowerShell',
        description: 'Anticipated execution of remote administrative scripts or automated discovery payloads.',
        indicators: ['Remote WMI / PowerShell remoting invocation likely'],
        relatedEventsCount: 0,
      },
      {
        id: 'persistence',
        name: 'Persistence',
        order: 4,
        status: 'not-reached',
        mitreTechniqueId: 'T1053.005',
        mitreTechniqueName: 'Scheduled Task/Job: Scheduled Task',
        description: 'Creation of persistent registry run keys or scheduled services for recurring execution.',
        indicators: ['Scheduled task creation event monitoring active'],
        relatedEventsCount: 0,
      },
      {
        id: 'privilege-escalation',
        name: 'Privilege Escalation',
        order: 5,
        status: 'not-reached',
        mitreTechniqueId: 'T1068',
        mitreTechniqueName: 'Exploitation for Privilege Escalation',
        description: 'Abuse of token impersonation privileges or kernel driver vulnerabilities to gain SYSTEM context.',
        indicators: ['SeImpersonatePrivilege monitoring armed'],
        relatedEventsCount: 0,
      },
      {
        id: 'credential-access',
        name: 'Credential Access',
        order: 6,
        status: 'predicted',
        confidence: 78,
        mitreTechniqueId: 'T1558.003',
        mitreTechniqueName: 'Steal or Forge Kerberos Tickets: Kerberoasting',
        description: 'Adversary trajectory strongly suggests SPN ticket extraction to crack offline service hashes.',
        indicators: ['High volume of TGS-REQ ticket queries for ServicePrincipalNames expected'],
        relatedEventsCount: 0,
      },
      {
        id: 'lateral-movement',
        name: 'Lateral Movement',
        order: 7,
        status: 'not-reached',
        mitreTechniqueId: 'T1021.002',
        mitreTechniqueName: 'Remote Services: SMB/Windows Admin Shares',
        description: 'Spreading across adjacent subnets to database clusters or backup repository nodes.',
        indicators: ['Egress to 10.0.8.0/24 subnet watched'],
        relatedEventsCount: 0,
      },
      {
        id: 'exfiltration',
        name: 'Exfiltration',
        order: 8,
        status: 'not-reached',
        mitreTechniqueId: 'T1048.003',
        mitreTechniqueName: 'Exfiltration Over Alternative Protocol: Unencrypted Network Protocol',
        description: 'Compression and staging of NTDS.dit domain directory database for extraction.',
        indicators: ['DNS tunneling & encrypted egress inspection enabled'],
        relatedEventsCount: 0,
      },
    ],
    forecastTimeline: [
      {
        stageId: 'credential-access',
        stageName: 'Credential Access (Kerberoasting)',
        probability: 78,
        estimatedTimeWindow: '10–20 mins',
        indicators: ['TGS-REQ ticket queries for SPN accounts', 'RC4 ticket encryption downgrade request'],
        confidence: 91,
        recommendedPreemptiveAction: 'Rotate all Kerberos service account keys and disable RC4 encryption suite on DC-01.',
      },
      {
        stageId: 'execution',
        stageName: 'Remote Execution & Discovery',
        probability: 64,
        estimatedTimeWindow: '30–60 mins',
        indicators: ['Encoded PowerShell execution flags (-enc)', 'AdFind / SharpHound LDAP query bursts'],
        confidence: 84,
        recommendedPreemptiveAction: 'Enable PowerShell Constrained Language Mode and ScriptBlock logging across DC-01.',
      },
      {
        stageId: 'lateral-movement',
        stageName: 'Lateral Propagation to DB Tier',
        probability: 52,
        estimatedTimeWindow: '1–2 hours',
        indicators: ['SMB connection attempts to DB-PROD-01 (10.0.8.44)', 'Pass-the-Hash / Overpass-the-Hash artifact'],
        confidence: 76,
        recommendedPreemptiveAction: 'Enforce micro-segmentation firewall rules isolating DC-01 management ports from DB subnet.',
      },
      {
        stageId: 'exfiltration',
        stageName: 'NTDS.dit Domain Extraction',
        probability: 38,
        estimatedTimeWindow: '2–6 hours',
        indicators: ['Volume Shadow Copy (vssadmin) snapshot creation', 'Outbound TLS connection to external fast-flux IP'],
        confidence: 68,
        recommendedPreemptiveAction: 'Restricted administrative privileges on NTDS folder and block outbound egress on non-standard ports.',
      },
    ],
    contributingFactors: [
      {
        id: 'cf-1',
        name: 'Kerberos Pre-Auth Failure Anomaly',
        category: 'Behavioral Anomaly',
        weight: 38,
        description: 'A rapid cluster of 8 failed pre-authentication attempts occurred in under 90 seconds prior to successful login.',
        evidence: 'Event ID 4625 (Status 0xC000006A) recorded 8 times between 23:42:15 and 23:43:40 UTC.',
      },
      {
        id: 'cf-2',
        name: 'Untrusted Source Geolocation & ASN',
        category: 'Threat Intelligence',
        weight: 26,
        description: 'Ingress IP address (194.26.29.114) belongs to a bulletproof hosting provider known for adversary proxy chains.',
        evidence: 'AS200052 flagged with a 92% threat score on multiple threat feeds.',
      },
      {
        id: 'cf-3',
        name: 'Privileged Service Account Off-Hours Usage',
        category: 'Identity Risk',
        weight: 20,
        description: 'Service account "svc_backup_admin" was authenticated interactively outside its regular maintenance window.',
        evidence: 'Logon type 10 (RemoteInteractive) observed at 23:48:12 UTC; expected scheduled job type 4.',
      },
      {
        id: 'cf-4',
        name: 'Unregistered TLS JA4 Device Fingerprint',
        category: 'Endpoint Telemetry',
        weight: 16,
        description: 'The TLS client fingerprint did not match any enterprise-managed workstation or domain asset profile.',
        evidence: 'Observed JA4: t13d1516h2_8daaf6152771_010203040506.',
      },
    ],
    plainLanguageExplanation: 'SentinelFlow detected a Credential Attack targeting the primary Domain Controller (DC-01). An external actor at IP 194.26.29.114 executed rapid credential guessing against the privileged "svc_backup_admin" account and achieved logon access. Based on behavioral sequences, the adversary is predicted (78% probability) to attempt Kerberoasting ticket extraction within the next 10–20 minutes.',
    simulatedActions: [
      {
        id: 'block_ip',
        name: 'Block Ingress IP at Perimeter Firewall',
        description: 'Instantly drop all incoming TCP/UDP traffic from 194.26.29.114 at edge firewalls and load balancers.',
        category: 'Network',
        riskReductionPercent: 64,
        predictedRiskScore: 31,
        impactAnalysis: 'Low operational disruption. Eliminates active adversary connection channel without affecting internal systems.',
        recommendationText: 'Apply perimeter block rule on border firewalls for IP 194.26.29.114.',
      },
      {
        id: 'isolate_host',
        name: 'Network-Isolate Host DC-01',
        description: 'Sever all network connections except SentinelFlow EDR management tunnel to stop lateral expansion.',
        category: 'Host',
        riskReductionPercent: 88,
        predictedRiskScore: 10,
        impactAnalysis: 'High business impact: Domain authentication will fail over to secondary controller (DC-02).',
        recommendationText: 'Perform soft isolation of DC-01 and route authentication requests to DC-02.',
      },
      {
        id: 'reset_creds',
        name: 'Revoke Kerberos Tickets & Reset Password',
        description: 'Invalidate all active Kerberos TGTs for "svc_backup_admin", force password rotation, and terminate sessions.',
        category: 'Identity',
        riskReductionPercent: 72,
        predictedRiskScore: 24,
        impactAnalysis: 'Zero user disruption. Requires updating automated backup cron credentials post-rotation.',
        recommendationText: 'Immediately reset svc_backup_admin credentials and flush Kerberos ticket cache on domain controllers.',
      },
      {
        id: 'enable_mfa',
        name: 'Enforce Step-Up Conditional MFA',
        description: 'Require FIDO2 / hardware token authentication for all interactive sessions to domain infrastructure.',
        category: 'Policy',
        riskReductionPercent: 55,
        predictedRiskScore: 39,
        impactAnalysis: 'Minimal impact: Prevents credential-only replay attacks for all administrative accounts.',
        recommendationText: 'Mandate hardware MFA for interactive domain administration.',
      },
      {
        id: 'enable_spn_alerting',
        name: 'Harden Kerberos Encryption (Disable RC4)',
        description: 'Enforce AES-256 Kerberos encryption and enable real-time alert on anomalous TGS-REQ SPN requests.',
        category: 'Policy',
        riskReductionPercent: 48,
        predictedRiskScore: 45,
        impactAnalysis: 'Prevents offline ticket cracking (Kerberoasting) attempts.',
        recommendationText: 'Enforce AES-256 for all service principal names and monitor Event ID 4769.',
      },
    ],
    recommendations: [
      {
        id: 'rec-1',
        priority: 'CRITICAL',
        action: 'Revoke and Reset "svc_backup_admin" Credentials',
        reason: 'Account is confirmed compromised via external IP logon. Active sessions remain valid.',
        affectedAsset: 'DC-01 / Active Directory',
        expectedBenefit: 'Immediate session termination; prevents credential reuse across domain.',
        actionCategory: 'IAM',
        simulatedReduction: 72,
      },
      {
        id: 'rec-2',
        priority: 'CRITICAL',
        action: 'Blacklist Perimeter Ingress IP 194.26.29.114',
        reason: 'Confirmed command-and-control / attack source origin flagged on threat intelligence networks.',
        affectedAsset: 'Perimeter Firewalls (Palo Alto / Fortinet)',
        expectedBenefit: 'Sever active TCP channel; halts telemetry exfiltration.',
        actionCategory: 'Firewall',
        simulatedReduction: 64,
      },
      {
        id: 'rec-3',
        priority: 'HIGH',
        action: 'Enable Kerberos SPN Request Anomaly Detection',
        reason: 'Forecasting engine indicates 78% probability of imminent Kerberoasting ticket extraction.',
        affectedAsset: 'DC-01 / SIEM Correlation Engine',
        expectedBenefit: 'Real-time alert on Event ID 4769 (TGS requests with RC4 cipher).',
        actionCategory: 'Monitoring',
        simulatedReduction: 48,
      },
      {
        id: 'rec-4',
        priority: 'HIGH',
        action: 'Isolate Host DC-01 for Forensic Memory Dump',
        reason: 'Validate whether memory injection or credential harvesting tools (Mimikatz) were executed.',
        affectedAsset: 'DC-01 (10.0.4.12)',
        expectedBenefit: 'Preserve volatile memory state; stop lateral propagation.',
        actionCategory: 'EDR',
        simulatedReduction: 88,
      },
      {
        id: 'rec-5',
        priority: 'MEDIUM',
        action: 'Audit Group Policy Restricted Admin Privileges',
        reason: 'Prevent administrative credentials from caching in LSASS on non-tier-0 servers.',
        affectedAsset: 'Domain-wide GPO',
        expectedBenefit: 'Harden fleet against Pass-the-Hash / LSASS dumping.',
        actionCategory: 'Patching',
        simulatedReduction: 35,
      },
    ],
    relatedEventIds: ['EVT-1001', 'EVT-1002', 'EVT-1003', 'EVT-1004'],
  },
  {
    id: 'THREAT-002',
    name: 'Brute Force Login Surge',
    risk: 'HIGH',
    riskScore: 79,
    confidence: 96,
    currentStage: 'Initial Access',
    currentStageId: 'initial-access',
    nextLikelyStage: 'Execution',
    nextLikelyProbability: 71,
    firstDetected: '2026-09-02 23:15:30',
    lastSeen: '4 mins ago (23:45:00)',
    affectedSystem: 'VPN-GW-01',
    affectedSystemIp: '10.0.1.1',
    sourceIp: '45.142.195.88',
    threatActor: 'Botnet Cluster (Mirai Variant)',
    status: 'Active',
    attackType: 'Distributed Password Spraying & Brute Force',
    summary: 'Sustained distributed password spray against enterprise SSL-VPN gateway across 45 distinct corporate usernames.',
    stages: [
      {
        id: 'reconnaissance',
        name: 'Reconnaissance',
        order: 1,
        status: 'completed',
        timestamp: '23:15:30',
        confidence: 98,
        mitreTechniqueId: 'T1589.002',
        mitreTechniqueName: 'Gather Victim Identity Information: Email Addresses',
        description: 'Targeted harvesting of corporate email addresses from public breach dumps.',
        indicators: ['Known username dictionary pattern observed'],
        relatedEventsCount: 1,
      },
      {
        id: 'initial-access',
        name: 'Initial Access',
        order: 2,
        status: 'current',
        timestamp: '23:45:00',
        confidence: 96,
        mitreTechniqueId: 'T1110.003',
        mitreTechniqueName: 'Brute Force: Password Spraying',
        description: 'Over 450 authentication attempts against SSL-VPN interface with rate limiting evasion.',
        indicators: ['Distributed IP rotations', 'High failed-to-successful login ratio'],
        relatedEventsCount: 5,
      },
      {
        id: 'execution',
        name: 'Execution',
        order: 3,
        status: 'predicted',
        confidence: 71,
        mitreTechniqueId: 'T1059.004',
        mitreTechniqueName: 'Command and Scripting Interpreter: Unix Shell',
        description: 'Anticipated internal network sweep once VPN tunnel is established.',
        indicators: ['VPN tunnel initialization followed by internal ICMP sweeps'],
        relatedEventsCount: 0,
      },
      {
        id: 'persistence',
        name: 'Persistence',
        order: 4,
        status: 'not-reached',
        mitreTechniqueId: 'T1136.001',
        mitreTechniqueName: 'Create Account: Local Account',
        description: 'Creation of secondary backdoor VPN profiles.',
        indicators: ['New VPN profile provisioning watched'],
        relatedEventsCount: 0,
      },
      {
        id: 'privilege-escalation',
        name: 'Privilege Escalation',
        order: 5,
        status: 'not-reached',
        mitreTechniqueId: 'T1078',
        mitreTechniqueName: 'Valid Accounts',
        description: 'Escalation to administrative VPN groups.',
        indicators: ['AD group modification attempts monitored'],
        relatedEventsCount: 0,
      },
      {
        id: 'credential-access',
        name: 'Credential Access',
        order: 6,
        status: 'not-reached',
        mitreTechniqueId: 'T1003',
        mitreTechniqueName: 'OS Credential Dumping',
        description: 'Dumping authentication tokens from VPN gateway memory.',
        indicators: ['Gateway process inspection enabled'],
        relatedEventsCount: 0,
      },
      {
        id: 'lateral-movement',
        name: 'Lateral Movement',
        order: 7,
        status: 'not-reached',
        mitreTechniqueId: 'T1021.001',
        mitreTechniqueName: 'Remote Services: Remote Desktop Protocol',
        description: 'Connecting to internal workstations via RDP over VPN.',
        indicators: ['Internal RDP connection alerts active'],
        relatedEventsCount: 0,
      },
      {
        id: 'exfiltration',
        name: 'Exfiltration',
        order: 8,
        status: 'not-reached',
        mitreTechniqueId: 'T1041',
        mitreTechniqueName: 'Exfiltration Over C2 Channel',
        description: 'Tunneling data out through the established VPN session.',
        indicators: ['High outbound volume monitoring active'],
        relatedEventsCount: 0,
      },
    ],
    forecastTimeline: [
      {
        stageId: 'execution',
        stageName: 'Internal Network Discovery',
        probability: 71,
        estimatedTimeWindow: '15–30 mins',
        indicators: ['Successful VPN login with subsequent ARP scanning'],
        confidence: 89,
        recommendedPreemptiveAction: 'Enforce rate-limiting and temporary lockout on targeted accounts.',
      },
      {
        stageId: 'lateral-movement',
        stageName: 'Internal RDP Probing',
        probability: 58,
        estimatedTimeWindow: '45–90 mins',
        indicators: ['Port 3389 connections from VPN pool to internal subnet'],
        confidence: 78,
        recommendedPreemptiveAction: 'Restrict VPN pool routing to only required corporate services.',
      },
    ],
    contributingFactors: [
      {
        id: 'cf-201',
        name: 'High-Volume Authentication Failure Spike',
        category: 'Behavioral Anomaly',
        weight: 44,
        description: 'VPN authentication failure rate increased by 1,400% compared to baseline 7-day average.',
        evidence: '452 failed logins recorded in 30 minutes from rotating external IP pool.',
      },
      {
        id: 'cf-202',
        name: 'Password Spray Signature Match',
        category: 'Pattern Anomaly',
        weight: 32,
        description: 'Each target user account tested with single common seasonal password before cycling.',
        evidence: 'Identified "Winter2026!" and "Welcome2026!" pattern.',
      },
      {
        id: 'cf-203',
        name: 'Reputation Feed Correlation',
        category: 'Threat Intelligence',
        weight: 24,
        description: 'Source IP 45.142.195.88 is a known exit node in an active brute-force botnet.',
        evidence: 'Listed on AbuseIPDB with 100% confidence rating.',
      },
    ],
    plainLanguageExplanation: 'SentinelFlow identified an automated password spray attack targeting the corporate VPN gateway (VPN-GW-01). Over 450 failed authentication attempts were detected from an external botnet node (45.142.195.88). If successful credentials are found, the attacker is forecasted (71% probability) to immediately initiate internal network discovery.',
    simulatedActions: [
      {
        id: 'block_ip_vpn',
        name: 'Block Source Subnet on Edge Router',
        description: 'Drop traffic from 45.142.195.0/24 subnet at the border router.',
        category: 'Network',
        riskReductionPercent: 70,
        predictedRiskScore: 24,
        impactAnalysis: 'Zero legitimate business impact; completely halts current botnet cluster.',
        recommendationText: 'Block subnet 45.142.195.0/24 on perimeter firewalls.',
      },
      {
        id: 'enable_vpn_mfa',
        name: 'Enforce Mandatory Push-Based MFA for VPN',
        description: 'Require instant mobile push verification for all incoming VPN connections.',
        category: 'Identity',
        riskReductionPercent: 82,
        predictedRiskScore: 14,
        impactAnalysis: 'Prevents credential spraying from succeeding even if passwords match.',
        recommendationText: 'Ensure all VPN profiles require Duo/Okta push MFA.',
      },
      {
        id: 'rate_limit_auth',
        name: 'Tighten VPN Gateway Rate Limiting',
        description: 'Drop connection requests exceeding 5 attempts per minute per source IP.',
        category: 'Policy',
        riskReductionPercent: 50,
        predictedRiskScore: 40,
        impactAnalysis: 'Significantly degrades botnet brute-force velocity.',
        recommendationText: 'Configure aggressive auth rate limiting on VPN-GW-01.',
      },
    ],
    recommendations: [
      {
        id: 'rec-201',
        priority: 'CRITICAL',
        action: 'Enforce Mandatory MFA on All VPN User Accounts',
        reason: 'Password spray attacks are completely mitigated when second-factor authentication is active.',
        affectedAsset: 'VPN-GW-01 / Identity Provider',
        expectedBenefit: 'Nullifies compromised password risks across entire remote workforce.',
        actionCategory: 'IAM',
        simulatedReduction: 82,
      },
      {
        id: 'rec-202',
        priority: 'HIGH',
        action: 'Blacklist Botnet Source IP Range 45.142.195.0/24',
        reason: 'Source of aggressive distributed authentication attacks.',
        affectedAsset: 'Perimeter Firewalls',
        expectedBenefit: 'Immediate reduction in inbound connection load and attack traffic.',
        actionCategory: 'Firewall',
        simulatedReduction: 70,
      },
    ],
    relatedEventIds: ['EVT-1005', 'EVT-1006'],
  },
  {
    id: 'THREAT-003',
    name: 'Suspicious Reconnaissance Scan',
    risk: 'MEDIUM',
    riskScore: 54,
    confidence: 88,
    currentStage: 'Reconnaissance',
    currentStageId: 'reconnaissance',
    nextLikelyStage: 'Initial Access',
    nextLikelyProbability: 46,
    firstDetected: '2026-09-02 22:10:00',
    lastSeen: '18 mins ago (23:30:12)',
    affectedSystem: 'WEB-PROD-01',
    affectedSystemIp: '10.0.2.15',
    sourceIp: '185.220.101.5',
    threatActor: 'Tor Exit Node / Anonymous Scanner',
    status: 'Investigating',
    attackType: 'Automated Vulnerability Sweep & Port Probing',
    summary: 'Systematic TCP SYN probing across web and database ports on public-facing DMZ server.',
    stages: [
      {
        id: 'reconnaissance',
        name: 'Reconnaissance',
        order: 1,
        status: 'current',
        timestamp: '23:30:12',
        confidence: 92,
        mitreTechniqueId: 'T1595.001',
        mitreTechniqueName: 'Active Scanning: Port Scanning',
        description: 'Comprehensive port probe targeting ports 80, 443, 8080, 8443, 3306, 5432.',
        indicators: ['SYN packets without ACK completion', 'High port sweep velocity'],
        relatedEventsCount: 3,
      },
      {
        id: 'initial-access',
        name: 'Initial Access',
        order: 2,
        status: 'predicted',
        confidence: 46,
        mitreTechniqueId: 'T1190',
        mitreTechniqueName: 'Exploit Public-Facing Application',
        description: 'Potential exploitation attempts against detected open web server ports.',
        indicators: ['Web request payloads with known CVE signatures'],
        relatedEventsCount: 0,
      },
      {
        id: 'execution',
        name: 'Execution',
        order: 3,
        status: 'not-reached',
        mitreTechniqueId: 'T1059',
        mitreTechniqueName: 'Command and Scripting Interpreter',
        description: 'Remote code execution payload delivery.',
        indicators: ['Web shell upload indicators watched'],
        relatedEventsCount: 0,
      },
      {
        id: 'persistence',
        name: 'Persistence',
        order: 4,
        status: 'not-reached',
        mitreTechniqueId: 'T1505.003',
        mitreTechniqueName: 'Server Software Component: Web Shell',
        description: 'Web shell dropped in public directory.',
        indicators: ['New PHP/JSP file creation alerts'],
        relatedEventsCount: 0,
      },
      {
        id: 'privilege-escalation',
        name: 'Privilege Escalation',
        order: 5,
        status: 'not-reached',
        mitreTechniqueId: 'T1068',
        mitreTechniqueName: 'Exploitation for Privilege Escalation',
        description: 'Local root exploit execution.',
        indicators: ['Privilege escalation monitoring armed'],
        relatedEventsCount: 0,
      },
      {
        id: 'credential-access',
        name: 'Credential Access',
        order: 6,
        status: 'not-reached',
        mitreTechniqueId: 'T1552',
        mitreTechniqueName: 'Unsecured Credentials',
        description: 'Reading configuration files for DB credentials.',
        indicators: ['Config file access monitoring active'],
        relatedEventsCount: 0,
      },
      {
        id: 'lateral-movement',
        name: 'Lateral Movement',
        order: 7,
        status: 'not-reached',
        mitreTechniqueId: 'T1210',
        mitreTechniqueName: 'Exploitation of Remote Services',
        description: 'Lateral spread from DMZ to internal database network.',
        indicators: ['DMZ-to-internal network alerts armed'],
        relatedEventsCount: 0,
      },
      {
        id: 'exfiltration',
        name: 'Exfiltration',
        order: 8,
        status: 'not-reached',
        mitreTechniqueId: 'T1048',
        mitreTechniqueName: 'Exfiltration Over Alternative Protocol',
        description: 'Data exfiltration over web traffic.',
        indicators: ['Egress monitoring enabled'],
        relatedEventsCount: 0,
      },
    ],
    forecastTimeline: [
      {
        stageId: 'initial-access',
        stageName: 'Public Web Exploit Probing',
        probability: 46,
        estimatedTimeWindow: '1–3 hours',
        indicators: ['HTTP POST payloads containing path traversal or SQL injection strings'],
        confidence: 72,
        recommendedPreemptiveAction: 'Ensure WAF rules are actively blocking known CVE attack patterns.',
      },
    ],
    contributingFactors: [
      {
        id: 'cf-301',
        name: 'Rapid Port Sweep Detection',
        category: 'Network Pattern',
        weight: 55,
        description: 'Over 120 unique TCP ports probed sequentially within 4 seconds.',
        evidence: 'Suricata Alert SID 2001219 (GPL SCAN nmap TCP).',
      },
      {
        id: 'cf-302',
        name: 'Tor Exit Node Source',
        category: 'Threat Intelligence',
        weight: 45,
        description: 'Origin IP 185.220.101.5 is an active Tor directory exit node.',
        evidence: 'Matched against Tor Project published exit list.',
      },
    ],
    plainLanguageExplanation: 'SentinelFlow detected network reconnaissance against the production web server (WEB-PROD-01). A Tor exit node scanned multiple service ports. While no breach has occurred, the actor is likely cataloging open services to launch targeted web exploitation attempts (46% probability).',
    simulatedActions: [
      {
        id: 'block_tor_exits',
        name: 'Block All Known Tor Exit Nodes at WAF',
        description: 'Automatically drop HTTP/HTTPS and TCP connections originating from Tor exit addresses.',
        category: 'Network',
        riskReductionPercent: 75,
        predictedRiskScore: 14,
        impactAnalysis: 'Negligible business impact: Legitimate enterprise clients do not route via Tor.',
        recommendationText: 'Enable Tor exit node blocking on Cloudflare / AWS WAF.',
      },
      {
        id: 'close_unused_ports',
        name: 'Close Non-Standard DMZ Ports on Security Group',
        description: 'Restrict ingress on WEB-PROD-01 strictly to ports 80 and 443.',
        category: 'Policy',
        riskReductionPercent: 60,
        predictedRiskScore: 22,
        impactAnalysis: 'Removes potential attack vectors (3306, 8080) from public visibility.',
        recommendationText: 'Update AWS Security Group / firewall to close all ports except 80 and 443.',
      },
    ],
    recommendations: [
      {
        id: 'rec-301',
        priority: 'MEDIUM',
        action: 'Enable Tor Exit Node Ingress Filtering',
        reason: 'Eliminates anonymous automated reconnaissance sweeps targeting DMZ applications.',
        affectedAsset: 'WAF / Edge Perimeter',
        expectedBenefit: 'Reduces scan noise and blocks initial probing vectors.',
        actionCategory: 'Firewall',
        simulatedReduction: 75,
      },
    ],
    relatedEventIds: ['EVT-1007', 'EVT-1008'],
  },
  {
    id: 'THREAT-004',
    name: 'Privilege Escalation via Token Impersonation',
    risk: 'CRITICAL',
    riskScore: 93,
    confidence: 95,
    currentStage: 'Privilege Escalation',
    currentStageId: 'privilege-escalation',
    nextLikelyStage: 'Lateral Movement',
    nextLikelyProbability: 84,
    firstDetected: '2026-09-02 23:35:10',
    lastSeen: '8 mins ago (23:41:20)',
    affectedSystem: 'APP-PROD-02',
    affectedSystemIp: '10.0.3.18',
    sourceIp: '10.0.3.18 (Local)',
    threatActor: 'Active Adversary (Post-Exploitation)',
    status: 'Active',
    attackType: 'SeImpersonate Token Stealing / Potato Exploit',
    summary: 'Low-privileged IIS service account invoked named pipe impersonation to acquire NT AUTHORITY\\SYSTEM privileges.',
    stages: [
      {
        id: 'reconnaissance',
        name: 'Reconnaissance',
        order: 1,
        status: 'completed',
        timestamp: '23:35:10',
        confidence: 90,
        mitreTechniqueId: 'T1082',
        mitreTechniqueName: 'System Information Discovery',
        description: 'Local environment enumeration of enabled privileges.',
        indicators: ['whoami /priv command execution'],
        relatedEventsCount: 1,
      },
      {
        id: 'initial-access',
        name: 'Initial Access',
        order: 2,
        status: 'completed',
        timestamp: '23:36:45',
        confidence: 92,
        mitreTechniqueId: 'T1190',
        mitreTechniqueName: 'Exploit Public-Facing Application',
        description: 'File upload vulnerability exploitation leading to web shell.',
        indicators: ['Anomalous ASPX write in /uploads/ directory'],
        relatedEventsCount: 2,
      },
      {
        id: 'execution',
        name: 'Execution',
        order: 3,
        status: 'completed',
        timestamp: '23:38:00',
        confidence: 94,
        mitreTechniqueId: 'T1059.001',
        mitreTechniqueName: 'Command and Scripting Interpreter: PowerShell',
        description: 'Execution of encoded privilege escalation binary.',
        indicators: ['cmd.exe spawned by w3wp.exe'],
        relatedEventsCount: 2,
      },
      {
        id: 'persistence',
        name: 'Persistence',
        order: 4,
        status: 'completed',
        timestamp: '23:39:15',
        confidence: 88,
        mitreTechniqueId: 'T1543.003',
        mitreTechniqueName: 'Create or Modify System Process: Windows Service',
        description: 'Creation of maintenance service configured to run on boot.',
        indicators: ['Event ID 7045 (New Service Installed)'],
        relatedEventsCount: 1,
      },
      {
        id: 'privilege-escalation',
        name: 'Privilege Escalation',
        order: 5,
        status: 'current',
        timestamp: '23:41:20',
        confidence: 95,
        mitreTechniqueId: 'T1134.001',
        mitreTechniqueName: 'Access Token Manipulation: Token Impersonation/Theft',
        description: 'Successful exploitation of SeImpersonatePrivilege via named pipe rogue potato tool.',
        indicators: ['Token elevation from IIS_IUSRS to NT AUTHORITY\\SYSTEM'],
        relatedEventsCount: 3,
      },
      {
        id: 'credential-access',
        name: 'Credential Access',
        order: 6,
        status: 'predicted',
        confidence: 76,
        mitreTechniqueId: 'T1003.001',
        mitreTechniqueName: 'OS Credential Dumping: LSASS Memory',
        description: 'Dumping LSASS process memory to harvest domain credentials.',
        indicators: ['lsass.exe memory read handle creation expected'],
        relatedEventsCount: 0,
      },
      {
        id: 'lateral-movement',
        name: 'Lateral Movement',
        order: 7,
        status: 'predicted',
        confidence: 84,
        mitreTechniqueId: 'T1021.002',
        mitreTechniqueName: 'Remote Services: SMB/Windows Admin Shares',
        description: 'Propagating to adjacent core database and file server nodes.',
        indicators: ['Network connection from APP-PROD-02 to internal DB tier'],
        relatedEventsCount: 0,
      },
      {
        id: 'exfiltration',
        name: 'Exfiltration',
        order: 8,
        status: 'not-reached',
        mitreTechniqueId: 'T1041',
        mitreTechniqueName: 'Exfiltration Over C2 Channel',
        description: 'Exfiltrating application database connection secrets.',
        indicators: ['Outbound data transfer monitoring active'],
        relatedEventsCount: 0,
      },
    ],
    forecastTimeline: [
      {
        stageId: 'lateral-movement',
        stageName: 'Lateral SMB Spread to Database Cluster',
        probability: 84,
        estimatedTimeWindow: '5–15 mins',
        indicators: ['SMB admin share authentication from APP-PROD-02 to DB-PROD-01'],
        confidence: 94,
        recommendedPreemptiveAction: 'Immediately isolate APP-PROD-02 from internal application subnet.',
      },
      {
        stageId: 'credential-access',
        stageName: 'LSASS Process Memory Dumping',
        probability: 76,
        estimatedTimeWindow: '10–25 mins',
        indicators: ['Process access requests targeting lsass.exe with PROCESS_VM_READ permissions'],
        confidence: 88,
        recommendedPreemptiveAction: 'Enable LSA Protection (RunAsPPL) and Microsoft Defender Credential Guard.',
      },
    ],
    contributingFactors: [
      {
        id: 'cf-401',
        name: 'Process Parent-Child Execution Anomaly',
        category: 'Endpoint Telemetry',
        weight: 42,
        description: 'Web server worker process (w3wp.exe) spawned interactive command interpreter (cmd.exe).',
        evidence: 'Sysmon Event ID 1: ParentImage w3wp.exe spawned Image cmd.exe with SYSTEM token.',
      },
      {
        id: 'cf-402',
        name: 'Named Pipe Impersonation Signature',
        category: 'Behavioral Anomaly',
        weight: 35,
        description: 'Exploitation signature matching GodPotato / SweetPotato named pipe reflection.',
        evidence: 'Pipe name "\\\\.\\pipe\\epmapper" opened by non-SYSTEM identity.',
      },
      {
        id: 'cf-403',
        name: 'New Windows Service Registration',
        category: 'Identity Risk',
        weight: 23,
        description: 'A service named "WinAppUpdateSvc" was registered with an executable in C:\\Windows\\Temp.',
        evidence: 'System Event ID 7045 registered at 23:39:15 UTC.',
      },
    ],
    plainLanguageExplanation: 'SentinelFlow identified an active Privilege Escalation incident on application server APP-PROD-02. An attacker exploited a web vulnerability, uploaded a payload, and abused Windows token privileges to elevate to full SYSTEM administrator access. The attacker is projected (84% probability) to begin lateral propagation to the corporate database within 5–15 minutes.',
    simulatedActions: [
      {
        id: 'isolate_app_host',
        name: 'Isolate Host APP-PROD-02',
        description: 'Immediately sever all network routes to APP-PROD-02 via EDR micro-isolation.',
        category: 'Host',
        riskReductionPercent: 91,
        predictedRiskScore: 8,
        impactAnalysis: 'App traffic will failover to APP-PROD-01. Completely contains adversary.',
        recommendationText: 'Enact immediate endpoint isolation on APP-PROD-02.',
      },
      {
        id: 'kill_malicious_service',
        name: 'Terminate Rogue Process Tree & Service',
        description: 'Kill malicious cmd.exe child processes and delete WinAppUpdateSvc service.',
        category: 'Host',
        riskReductionPercent: 65,
        predictedRiskScore: 33,
        impactAnalysis: 'Neutralizes active execution payload on the host.',
        recommendationText: 'Stop and delete malicious service WinAppUpdateSvc.',
      },
      {
        id: 'block_lateral_smb',
        name: 'Block Inter-VLAN SMB Traffic (Port 445)',
        description: 'Prevent APP subnet from initiating direct SMB/RDP connections to DB tier.',
        category: 'Network',
        riskReductionPercent: 78,
        predictedRiskScore: 20,
        impactAnalysis: 'Prevents lateral jump while preserving forensic state.',
        recommendationText: 'Apply internal firewall rule blocking 10.0.3.0/24 -> 10.0.8.0/24 over port 445.',
      },
    ],
    recommendations: [
      {
        id: 'rec-401',
        priority: 'CRITICAL',
        action: 'Network-Isolate APP-PROD-02 Immediately',
        reason: 'Host is compromised with full SYSTEM privileges and poised for lateral spread.',
        affectedAsset: 'APP-PROD-02 (10.0.3.18)',
        expectedBenefit: 'Hard containment of adversary; halts database tier compromise.',
        actionCategory: 'EDR',
        simulatedReduction: 91,
      },
      {
        id: 'rec-402',
        priority: 'CRITICAL',
        action: 'Block Internal Subnet Lateral SMB (Port 445)',
        reason: 'Adversary trajectory points directly to lateral propagation to DB-PROD-01.',
        affectedAsset: 'Internal Core Switch / Firewall',
        expectedBenefit: 'Sever lateral expansion vectors across VLAN boundaries.',
        actionCategory: 'Firewall',
        simulatedReduction: 78,
      },
      {
        id: 'rec-403',
        priority: 'HIGH',
        action: 'Enable LSA Protection and Credential Guard',
        reason: 'Prevents unprivileged processes from reading plaintext secrets from LSASS memory.',
        affectedAsset: 'All Windows Server Fleet',
        expectedBenefit: 'Systemic mitigation against Mimikatz credential dumping.',
        actionCategory: 'Patching',
        simulatedReduction: 60,
      },
    ],
    relatedEventIds: ['EVT-1009', 'EVT-1010', 'EVT-1011'],
  },
  {
    id: 'THREAT-005',
    name: 'Lateral Movement via Remote WMI',
    risk: 'HIGH',
    riskScore: 82,
    confidence: 91,
    currentStage: 'Lateral Movement',
    currentStageId: 'lateral-movement',
    nextLikelyStage: 'Exfiltration',
    nextLikelyProbability: 68,
    firstDetected: '2026-09-02 23:20:00',
    lastSeen: '12 mins ago (23:37:45)',
    affectedSystem: 'FILE-SRV-01',
    affectedSystemIp: '10.0.5.22',
    sourceIp: '10.0.3.18 (Internal)',
    threatActor: 'Correlated with THREAT-004',
    status: 'Active',
    attackType: 'Remote WMI Execution & Admin Share Abuse',
    summary: 'Adversary leveraged compromised domain administrative credentials to execute remote commands via WMI on the corporate file server.',
    stages: [
      {
        id: 'reconnaissance',
        name: 'Reconnaissance',
        order: 1,
        status: 'completed',
        timestamp: '23:20:00',
        confidence: 94,
        mitreTechniqueId: 'T1018',
        mitreTechniqueName: 'Remote System Discovery',
        description: 'Discovery of file server shares across the subnet.',
        indicators: ['Net view and ping sweeps observed'],
        relatedEventsCount: 1,
      },
      {
        id: 'initial-access',
        name: 'Initial Access',
        order: 2,
        status: 'completed',
        timestamp: '23:25:30',
        confidence: 90,
        mitreTechniqueId: 'T1078.002',
        mitreTechniqueName: 'Valid Accounts: Domain Accounts',
        description: 'Stolen admin token used to authenticate to FILE-SRV-01.',
        indicators: ['Event ID 4624 Type 3 (Network Logon)'],
        relatedEventsCount: 2,
      },
      {
        id: 'execution',
        name: 'Execution',
        order: 3,
        status: 'completed',
        timestamp: '23:31:00',
        confidence: 95,
        mitreTechniqueId: 'T1047',
        mitreTechniqueName: 'Windows Management Instrumentation',
        description: 'WMI Win32_Process.Create executed to start discovery script.',
        indicators: ['WmiPrvSE.exe spawning powershell.exe'],
        relatedEventsCount: 2,
      },
      {
        id: 'persistence',
        name: 'Persistence',
        order: 4,
        status: 'not-reached',
        mitreTechniqueId: 'T1546',
        mitreTechniqueName: 'Event Triggered Execution',
        description: 'WMI event subscriptions for recurring trigger.',
        indicators: ['WMI consumer registration watched'],
        relatedEventsCount: 0,
      },
      {
        id: 'privilege-escalation',
        name: 'Privilege Escalation',
        order: 5,
        status: 'not-reached',
        mitreTechniqueId: 'T1068',
        mitreTechniqueName: 'Exploitation for Privilege Escalation',
        description: 'Already operating with domain administrator rights.',
        indicators: ['High privileges confirmed'],
        relatedEventsCount: 0,
      },
      {
        id: 'credential-access',
        name: 'Credential Access',
        order: 6,
        status: 'not-reached',
        mitreTechniqueId: 'T1003',
        mitreTechniqueName: 'OS Credential Dumping',
        description: 'Extracting file server SAM hashes.',
        indicators: ['SAM registry hive access alerts armed'],
        relatedEventsCount: 0,
      },
      {
        id: 'lateral-movement',
        name: 'Lateral Movement',
        order: 7,
        status: 'current',
        timestamp: '23:37:45',
        confidence: 91,
        mitreTechniqueId: 'T1021.002',
        mitreTechniqueName: 'Remote Services: SMB/Windows Admin Shares',
        description: 'Copying payload into \\\\FILE-SRV-01\\C$\\Windows\\Temp.',
        indicators: ['High SMB write rate to administrative share'],
        relatedEventsCount: 3,
      },
      {
        id: 'exfiltration',
        name: 'Exfiltration',
        order: 8,
        status: 'predicted',
        confidence: 68,
        mitreTechniqueId: 'T1560.001',
        mitreTechniqueName: 'Archive Collected Data: Archive via Utility',
        description: 'Compression of confidential finance and legal file shares.',
        indicators: ['7zip / winrar process invocation expected on file shares'],
        relatedEventsCount: 0,
      },
    ],
    forecastTimeline: [
      {
        stageId: 'exfiltration',
        stageName: 'Data Staging & Compression',
        probability: 68,
        estimatedTimeWindow: '20–40 mins',
        indicators: ['Mass file reads in \\\\FILE-SRV-01\\Confidential followed by 7z.exe archive creation'],
        confidence: 86,
        recommendedPreemptiveAction: 'Restrict file server egress and enforce read-only permissions on sensitive shares.',
      },
    ],
    contributingFactors: [
      {
        id: 'cf-501',
        name: 'Anomalous Remote WMI Process Creation',
        category: 'Endpoint Telemetry',
        weight: 48,
        description: 'WmiPrvSE.exe invoked PowerShell to run an encoded command on FILE-SRV-01 from host APP-PROD-02.',
        evidence: 'Sysmon Event ID 1: WmiPrvSE.exe -> powershell.exe -enc SQBFAFgA...',
      },
      {
        id: 'cf-502',
        name: 'C$ Administrative Share Access',
        category: 'Behavioral Anomaly',
        weight: 32,
        description: 'Direct file drop into administrative hidden share without typical user interaction.',
        evidence: 'Event ID 5145: Relative Target Name C$\\Windows\\Temp\\srvmgr.exe.',
      },
      {
        id: 'cf-503',
        name: 'Cross-VLAN Management Ingress',
        category: 'Network Pattern',
        weight: 20,
        description: 'WMI ports (135, dynamic RPC) queried across production application VLAN to file server VLAN.',
        evidence: 'Flow record: 10.0.3.18:49812 -> 10.0.5.22:135.',
      },
    ],
    plainLanguageExplanation: 'SentinelFlow identified lateral movement into the enterprise file server (FILE-SRV-01) originating from compromised node APP-PROD-02. The adversary utilized Remote WMI to execute discovery commands and staged a binary in the hidden C$ admin share. Forecasting models indicate a 68% probability that the attacker will begin mass data collection and archive compression within 20–40 minutes.',
    simulatedActions: [
      {
        id: 'isolate_file_srv',
        name: 'Network-Isolate FILE-SRV-01',
        description: 'Isolate file server from all internal VLANs except administrative jump box.',
        category: 'Host',
        riskReductionPercent: 85,
        predictedRiskScore: 12,
        impactAnalysis: 'File share access will be paused during containment.',
        recommendationText: 'Isolate FILE-SRV-01 to protect corporate data repositories.',
      },
      {
        id: 'disable_admin_shares',
        name: 'Disable Remote Administrative Shares (AutoShareWks/Server)',
        description: 'Block remote access to default hidden admin shares (C$, ADMIN$).',
        category: 'Policy',
        riskReductionPercent: 62,
        predictedRiskScore: 31,
        impactAnalysis: 'Halts unauthorized file drops across Windows fleet.',
        recommendationText: 'Disable administrative shares via GPO for all non-domain-controller servers.',
      },
      {
        id: 'block_wmi_ports',
        name: 'Block RPC Endpoint Mapper & WMI across Subnets',
        description: 'Restrict port 135 and dynamic RPC ports to authorized management jump hosts only.',
        category: 'Network',
        riskReductionPercent: 70,
        predictedRiskScore: 25,
        impactAnalysis: 'Prevents remote WMI execution from compromised application servers.',
        recommendationText: 'Apply firewall rule blocking port 135 and RPC between application and file subnets.',
      },
    ],
    recommendations: [
      {
        id: 'rec-501',
        priority: 'CRITICAL',
        action: 'Revoke Ingress Access from 10.0.3.18 to FILE-SRV-01',
        reason: 'Active remote execution channel confirmed from compromised host.',
        affectedAsset: 'Internal Core Firewall',
        expectedBenefit: 'Sever lateral bridge immediately.',
        actionCategory: 'Firewall',
        simulatedReduction: 75,
      },
      {
        id: 'rec-502',
        priority: 'HIGH',
        action: 'Enable File Integrity Monitoring on Sensitive Repositories',
        reason: 'Forecasting engine predicts imminent mass data archiving and compression.',
        affectedAsset: 'FILE-SRV-01 (10.0.5.22)',
        expectedBenefit: 'Instant alert on bulk file reads or unauthorized archive utilities.',
        actionCategory: 'EDR',
        simulatedReduction: 55,
      },
    ],
    relatedEventIds: ['EVT-1012', 'EVT-1013'],
  },
  {
    id: 'THREAT-006',
    name: 'Unusual Encrypted Egress Spike',
    risk: 'MEDIUM',
    riskScore: 68,
    confidence: 86,
    currentStage: 'Exfiltration',
    currentStageId: 'exfiltration',
    nextLikelyStage: 'Exfiltration',
    nextLikelyProbability: 92,
    firstDetected: '2026-09-02 23:25:00',
    lastSeen: '5 mins ago (23:44:30)',
    affectedSystem: 'DB-PROD-01',
    affectedSystemIp: '10.0.8.44',
    sourceIp: '198.51.100.24',
    threatActor: 'Automated Data Extraction Channel',
    status: 'Investigating',
    attackType: 'Anomalous High-Volume Outbound TLS Data Stream',
    summary: '4.2 GB of outbound encrypted data transmitted from the core database cluster to an unknown external VPS over port 8443.',
    stages: [
      {
        id: 'reconnaissance',
        name: 'Reconnaissance',
        order: 1,
        status: 'completed',
        timestamp: '23:25:00',
        confidence: 80,
        mitreTechniqueId: 'T1087',
        mitreTechniqueName: 'Account Discovery',
        description: 'Database table catalog query.',
        indicators: ['SQL table schema enumeration query'],
        relatedEventsCount: 1,
      },
      {
        id: 'initial-access',
        name: 'Initial Access',
        order: 2,
        status: 'completed',
        timestamp: '23:28:10',
        confidence: 85,
        mitreTechniqueId: 'T1078',
        mitreTechniqueName: 'Valid Accounts',
        description: 'Database access via internal application pool credentials.',
        indicators: ['Direct SQL connection from non-webhost node'],
        relatedEventsCount: 1,
      },
      {
        id: 'execution',
        name: 'Execution',
        order: 3,
        status: 'completed',
        timestamp: '23:32:00',
        confidence: 88,
        mitreTechniqueId: 'T1059',
        mitreTechniqueName: 'Command and Scripting Interpreter',
        description: 'Scripted export of customer database tables.',
        indicators: ['mysqldump / pg_dump execution'],
        relatedEventsCount: 1,
      },
      {
        id: 'persistence',
        name: 'Persistence',
        order: 4,
        status: 'not-reached',
        mitreTechniqueId: 'T1136',
        mitreTechniqueName: 'Create Account',
        description: 'Creation of secondary database admin user.',
        indicators: ['User creation alerts armed'],
        relatedEventsCount: 0,
      },
      {
        id: 'privilege-escalation',
        name: 'Privilege Escalation',
        order: 5,
        status: 'not-reached',
        mitreTechniqueId: 'T1068',
        mitreTechniqueName: 'Exploitation for Privilege Escalation',
        description: 'No further privilege needed.',
        indicators: ['DB superuser privileges confirmed'],
        relatedEventsCount: 0,
      },
      {
        id: 'credential-access',
        name: 'Credential Access',
        order: 6,
        status: 'completed',
        timestamp: '23:36:00',
        confidence: 85,
        mitreTechniqueId: 'T1552',
        mitreTechniqueName: 'Unsecured Credentials',
        description: 'Extraction of hashed password columns.',
        indicators: ['SELECT against user auth tables'],
        relatedEventsCount: 1,
      },
      {
        id: 'lateral-movement',
        name: 'Lateral Movement',
        order: 7,
        status: 'completed',
        timestamp: '23:39:00',
        confidence: 82,
        mitreTechniqueId: 'T1021',
        mitreTechniqueName: 'Remote Services',
        description: 'Pipelining database stream through staging server.',
        indicators: ['Internal tunnel session'],
        relatedEventsCount: 1,
      },
      {
        id: 'exfiltration',
        name: 'Exfiltration',
        order: 8,
        status: 'current',
        timestamp: '23:44:30',
        confidence: 92,
        mitreTechniqueId: 'T1048.002',
        mitreTechniqueName: 'Exfiltration Over Alternative Protocol: Asymmetric Encrypted Network Protocol',
        description: 'Continuous outbound TLS stream transferring 4.2 GB to external IP 198.51.100.24.',
        indicators: ['Bandwidth spike > 50 MB/s', 'Unknown destination certificate authority'],
        relatedEventsCount: 4,
      },
    ],
    forecastTimeline: [
      {
        stageId: 'exfiltration',
        stageName: 'Full Database Backup Exfiltration Completion',
        probability: 92,
        estimatedTimeWindow: '15–30 mins',
        indicators: ['Continuous sustained outbound throughput exceeding 40 MB/sec to 198.51.100.24'],
        confidence: 96,
        recommendedPreemptiveAction: 'Apply immediate egress block on perimeter firewall for DB cluster subnet.',
      },
    ],
    contributingFactors: [
      {
        id: 'cf-601',
        name: 'Volumetric Egress Bandwidth Anomaly',
        category: 'Network Pattern',
        weight: 52,
        description: 'Database server DB-PROD-01 generated 4.2 GB of outbound traffic; historical baseline is under 50 MB/day.',
        evidence: 'NetFlow telemetry recorded 4,294,967,296 bytes transferred in 12 minutes.',
      },
      {
        id: 'cf-602',
        name: 'Unregistered Destination IP & ASN',
        category: 'Threat Intelligence',
        weight: 30,
        description: 'Destination IP 198.51.100.24 has no business relationship and was provisioned within the last 48 hours.',
        evidence: 'WHOIS registration date: 2026-09-01.',
      },
      {
        id: 'cf-603',
        name: 'Non-Standard Secure Port Usage',
        category: 'Behavioral Anomaly',
        weight: 18,
        description: 'Egress initiated over port 8443 with self-signed certificate, bypassing standard HTTPS inspection.',
        evidence: 'TLS handshake issuer: CN=DefaultSelfSignedCert.',
      },
    ],
    plainLanguageExplanation: 'SentinelFlow detected anomalous high-volume data exfiltration from core database server DB-PROD-01. Over 4.2 GB of encrypted data has been sent to an unclassified external server (198.51.100.24). Forecasting indicates the transfer is 92% likely to complete full database extraction within the next 15–30 minutes unless network egress is severed immediately.',
    simulatedActions: [
      {
        id: 'block_db_egress',
        name: 'Block All Outbound Internet Egress for DB Subnet',
        description: 'Enforce zero-trust egress policy: Database cluster may only communicate with internal application servers.',
        category: 'Network',
        riskReductionPercent: 94,
        predictedRiskScore: 4,
        impactAnalysis: 'Zero legitimate business impact: Database servers should never have direct outbound internet access.',
        recommendationText: 'Block all outbound internet access from 10.0.8.0/24 subnet at core firewall.',
      },
      {
        id: 'terminate_db_session',
        name: 'Terminate Active Egress TCP Sessions',
        description: 'Force TCP RST on all active connections between DB-PROD-01 and 198.51.100.24.',
        category: 'Network',
        riskReductionPercent: 78,
        predictedRiskScore: 15,
        impactAnalysis: 'Immediately halts current exfiltration stream.',
        recommendationText: 'Send TCP RST packets to kill session to 198.51.100.24.',
      },
    ],
    recommendations: [
      {
        id: 'rec-601',
        priority: 'CRITICAL',
        action: 'Enforce Strict Zero-Trust Outbound Egress Block on DB Subnet',
        reason: 'Database servers must not have direct egress to public internet destinations.',
        affectedAsset: 'Database Subnet (10.0.8.0/24) / Perimeter Firewall',
        expectedBenefit: 'Instantly stops current and future data exfiltration attempts.',
        actionCategory: 'Firewall',
        simulatedReduction: 94,
      },
      {
        id: 'rec-602',
        priority: 'HIGH',
        action: 'Perform Database Access & Query Audit',
        reason: 'Identify exact customer tables and record volumes queried during the incident.',
        affectedAsset: 'DB-PROD-01 (10.0.8.44)',
        expectedBenefit: 'Determine regulatory breach scope (GDPR/HIPAA notification requirements).',
        actionCategory: 'IAM',
        simulatedReduction: 40,
      },
    ],
    relatedEventIds: ['EVT-1014', 'EVT-1015'],
  },
];

export const seedSystems: MonitoredSystem[] = [
  {
    id: 'SYS-001',
    name: 'DC-01',
    ip: '10.0.4.12',
    type: 'Domain Controller',
    os: 'Windows Server 2022 Datacenter',
    status: 'Critical',
    riskScore: 87,
    activeThreatsCount: 1,
    lastSeen: 'Live (1 min ago)',
    assignedThreatId: 'THREAT-001',
    agentVersion: 'v4.2.1-prod',
  },
  {
    id: 'SYS-002',
    name: 'APP-PROD-02',
    ip: '10.0.3.18',
    type: 'Web Server',
    os: 'Windows Server 2019',
    status: 'Critical',
    riskScore: 93,
    activeThreatsCount: 1,
    lastSeen: 'Live (8 mins ago)',
    assignedThreatId: 'THREAT-004',
    agentVersion: 'v4.2.1-prod',
  },
  {
    id: 'SYS-003',
    name: 'VPN-GW-01',
    ip: '10.0.1.1',
    type: 'Cloud Gateway',
    os: 'Palo Alto PAN-OS 11.0',
    status: 'At Risk',
    riskScore: 79,
    activeThreatsCount: 1,
    lastSeen: 'Live (4 mins ago)',
    assignedThreatId: 'THREAT-002',
    agentVersion: 'v3.9.0-gw',
  },
  {
    id: 'SYS-004',
    name: 'FILE-SRV-01',
    ip: '10.0.5.22',
    type: 'File Server',
    os: 'Windows Server 2022',
    status: 'At Risk',
    riskScore: 82,
    activeThreatsCount: 1,
    lastSeen: 'Live (12 mins ago)',
    assignedThreatId: 'THREAT-005',
    agentVersion: 'v4.2.1-prod',
  },
  {
    id: 'SYS-005',
    name: 'DB-PROD-01',
    ip: '10.0.8.44',
    type: 'Database Server',
    os: 'Red Hat Enterprise Linux 9.2',
    status: 'At Risk',
    riskScore: 68,
    activeThreatsCount: 1,
    lastSeen: 'Live (5 mins ago)',
    assignedThreatId: 'THREAT-006',
    agentVersion: 'v4.1.8-lnx',
  },
  {
    id: 'SYS-006',
    name: 'WEB-PROD-01',
    ip: '10.0.2.15',
    type: 'Web Server',
    os: 'Ubuntu 24.04 LTS',
    status: 'At Risk',
    riskScore: 54,
    activeThreatsCount: 1,
    lastSeen: 'Live (18 mins ago)',
    assignedThreatId: 'THREAT-003',
    agentVersion: 'v4.2.0-lnx',
  },
  {
    id: 'SYS-007',
    name: 'DC-02',
    ip: '10.0.4.13',
    type: 'Domain Controller',
    os: 'Windows Server 2022 Datacenter',
    status: 'Healthy',
    riskScore: 12,
    activeThreatsCount: 0,
    lastSeen: 'Live (Just now)',
    agentVersion: 'v4.2.1-prod',
  },
  {
    id: 'SYS-008',
    name: 'APP-PROD-01',
    ip: '10.0.3.17',
    type: 'Web Server',
    os: 'Windows Server 2022',
    status: 'Healthy',
    riskScore: 16,
    activeThreatsCount: 0,
    lastSeen: 'Live (Just now)',
    agentVersion: 'v4.2.1-prod',
  },
  {
    id: 'SYS-009',
    name: 'SEC-SIEM-01',
    ip: '10.0.9.10',
    type: 'Cloud Gateway',
    os: 'Debian 12 Bookworm',
    status: 'Healthy',
    riskScore: 8,
    activeThreatsCount: 0,
    lastSeen: 'Live (Just now)',
    agentVersion: 'v4.2.1-prod',
  },
  {
    id: 'SYS-010',
    name: 'WS-EXEC-09',
    ip: '10.0.6.104',
    type: 'Workstation',
    os: 'Windows 11 Enterprise 23H2',
    status: 'Healthy',
    riskScore: 14,
    activeThreatsCount: 0,
    lastSeen: 'Live (Just now)',
    agentVersion: 'v4.2.1-prod',
  },
];

export const seedEvents: SecurityEvent[] = [
  {
    id: 'EVT-1001',
    timestamp: '2026-09-02 23:42:01',
    event: 'SYN Port Sweep on Kerberos & LDAP Ports',
    source: 'Suricata IDS / Sensor-DMZ',
    sourceIp: '194.26.29.114',
    destination: 'DC-01',
    destinationIp: '10.0.4.12',
    severity: 'MEDIUM',
    category: 'Network Connection',
    details: 'TCP SYN scan detected probing destination ports 88 (Kerberos), 389 (LDAP), and 445 (SMB) within 250ms.',
    threatId: 'THREAT-001',
    rawPayload: {
      alert: 'GPL SCAN nmap TCP',
      proto: 'TCP',
      src_ip: '194.26.29.114',
      dest_ip: '10.0.4.12',
      dest_ports: [88, 389, 445],
      flags: 'SYN',
    },
  },
  {
    id: 'EVT-1002',
    timestamp: '2026-09-02 23:43:15',
    event: 'Kerberos Pre-Auth Failure Burst (Event ID 4625)',
    source: 'Windows Security Event Log',
    sourceIp: '194.26.29.114',
    destination: 'DC-01',
    destinationIp: '10.0.4.12',
    severity: 'HIGH',
    category: 'Authentication',
    details: 'Account "svc_backup_admin" failed pre-authentication 8 times in 85 seconds. Status: 0xC000006A (Wrong Password).',
    threatId: 'THREAT-001',
    rawPayload: {
      event_id: 4625,
      target_user: 'svc_backup_admin',
      status: '0xC000006A',
      failure_count: 8,
      workstation: 'UNKNOWN',
    },
  },
  {
    id: 'EVT-1003',
    timestamp: '2026-09-02 23:48:12',
    event: 'Successful Logon for Privileged Account (Event ID 4624)',
    source: 'Windows Security Event Log',
    sourceIp: '194.26.29.114',
    destination: 'DC-01',
    destinationIp: '10.0.4.12',
    severity: 'CRITICAL',
    category: 'Authentication',
    details: 'Logon Type 10 (RemoteInteractive) succeeded for svc_backup_admin from unregistered TLS client JA4 fingerprint.',
    threatId: 'THREAT-001',
    rawPayload: {
      event_id: 4624,
      target_user: 'svc_backup_admin',
      logon_type: 10,
      ja4_fingerprint: 't13d1516h2_8daaf6152771_010203040506',
    },
  },
  {
    id: 'EVT-1004',
    timestamp: '2026-09-02 23:49:05',
    event: 'Anomalous TGS-REQ Kerberos Ticket Query',
    source: 'SentinelFlow EDR Agent',
    sourceIp: '10.0.4.12',
    destination: 'DC-01',
    destinationIp: '10.0.4.12',
    severity: 'HIGH',
    category: 'Privilege',
    details: 'Query issued for SPN MSSQLSvc/db-prod-01.corp.internal:1433 requesting RC4 encryption ticket.',
    threatId: 'THREAT-001',
    rawPayload: {
      event_id: 4769,
      service_name: 'MSSQLSvc/db-prod-01.corp.internal:1433',
      ticket_encryption_type: '0x17 (RC4-HMAC)',
    },
  },
  {
    id: 'EVT-1005',
    timestamp: '2026-09-02 23:41:20',
    event: 'Token Impersonation: SeImpersonatePrivilege Abuse',
    source: 'Microsoft Defender for Endpoint',
    sourceIp: '10.0.3.18',
    destination: 'APP-PROD-02',
    destinationIp: '10.0.3.18',
    severity: 'CRITICAL',
    category: 'Privilege',
    details: 'w3wp.exe spawned cmd.exe creating named pipe "\\\\.\\pipe\\epmapper" with elevated NT AUTHORITY\\SYSTEM token.',
    threatId: 'THREAT-004',
    rawPayload: {
      parent_process: 'w3wp.exe',
      child_process: 'cmd.exe',
      token_elevated: 'NT AUTHORITY\\SYSTEM',
      technique: 'T1134.001',
    },
  },
  {
    id: 'EVT-1006',
    timestamp: '2026-09-02 23:44:30',
    event: 'Outbound High-Bandwidth TLS Stream on Non-Standard Port',
    source: 'Zeek / Network Flow Monitor',
    sourceIp: '10.0.8.44',
    destination: 'External VPS (198.51.100.24)',
    destinationIp: '198.51.100.24',
    severity: 'HIGH',
    category: 'Network Connection',
    details: 'Database node transferred 4.2 GB data over destination port 8443 in 12-minute window.',
    threatId: 'THREAT-006',
    rawPayload: {
      bytes_sent: 4294967296,
      duration_sec: 720,
      dest_port: 8443,
      protocol: 'TLSv1.3',
    },
  },
  {
    id: 'EVT-1007',
    timestamp: '2026-09-02 23:45:00',
    event: 'Password Spray Burst Detected on VPN Gateway',
    source: 'Palo Alto GlobalProtect Syslog',
    sourceIp: '45.142.195.88',
    destination: 'VPN-GW-01',
    destinationIp: '10.0.1.1',
    severity: 'HIGH',
    category: 'Authentication',
    details: '452 failed authentication attempts against SSL-VPN interface within 30 minutes.',
    threatId: 'THREAT-002',
    rawPayload: {
      auth_failures: 452,
      unique_usernames: 45,
      interval_sec: 1800,
    },
  },
  {
    id: 'EVT-1008',
    timestamp: '2026-09-02 23:46:10',
    event: 'Scheduled Security Log Integrity Verification',
    source: 'SentinelFlow Health Daemon',
    sourceIp: '10.0.9.10',
    destination: 'All Monitored Fleet',
    severity: 'INFO',
    category: 'Authentication',
    details: 'Automated cryptographic hash chain audit passed for all ingested SIEM/EDR log streams.',
    rawPayload: {
      audit_result: 'PASS',
      chain_valid: true,
    },
  },
];
