import React from 'react';
import { useThreatContext } from '../context/ThreatContext';
import { PageHeader } from '../components/common/PageHeader';
import { ThreatSelectorDropdown } from '../components/common/ThreatSelectorDropdown';
import { RecommendationsList } from '../components/recommendations/RecommendationsList';
import { Button } from '../components/common/Button';
import { Card } from '../components/common/Card';
import { CheckCircle2, FlaskConical, Download, ShieldCheck, AlertCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export const RecommendationsPage: React.FC = () => {
  const { selectedThreat } = useThreatContext();
  const navigate = useNavigate();

  return (
    <div className="space-y-6">
      <PageHeader
        title="Prioritized Security Action Recommendations"
        description="Prescriptive, impact-scored remediation steps organized by operational urgency to neutralize active threats and harden infrastructure."
        badge={
          <span className="text-xs font-bold text-slate-700 bg-slate-100 px-2.5 py-1 rounded-md border border-slate-300">
            {selectedThreat.recommendations.length} Action Items
          </span>
        }
        actions={
          <div className="flex items-center gap-3">
            <ThreatSelectorDropdown />
            <Button
              variant="outline"
              size="md"
              onClick={() => navigate('/what-if')}
              icon={<FlaskConical className="h-4 w-4 text-indigo-600" />}
            >
              Simulate in Sandbox
            </Button>
          </div>
        }
      />

      {/* Threat Context Bar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs">
        <div>
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 block">
            Target Threat Dossier
          </span>
          <div className="font-bold text-slate-900 text-sm mt-0.5">
            {selectedThreat.name} — <span className="font-mono text-indigo-700">{selectedThreat.affectedSystem}</span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-600 font-medium">
            Baseline Risk: <strong className="text-red-600">{selectedThreat.riskScore}/100</strong>
          </span>
        </div>
      </div>

      {/* Main Recommendations List */}
      <RecommendationsList
        recommendations={selectedThreat.recommendations}
        threatName={selectedThreat.name}
      />

      {/* Advisory Execution Notice */}
      <div className="p-4 rounded-xl bg-slate-100 border border-slate-200 flex items-start gap-3 text-xs text-slate-600">
        <AlertCircle className="h-4 w-4 text-slate-500 shrink-0 mt-0.5" />
        <div>
          <strong className="text-slate-800 font-bold block mb-0.5">SOC Tier-3 Governance Note:</strong>
          Recommendations are generated by SentinelFlow AI based on simulated impact modeling. In accordance with enterprise change management guidelines, actions are not executed automatically and require authorization from certified SOC leads or system administrators.
        </div>
      </div>
    </div>
  );
};
